### ISSUE TITLE
Base64 not suited for sanitizing database inputs

### ISSUE THREAD

**Issue by AlexCMueller** [HTSTEM/discord-bot#15]
SQL injection is currently *probably* impossible under the current revision, due to the use of base64 to sanitize inputs. However, there are multiple issues with this.

1) Base64 is not designed to sanitize database inputs. Output from a base64 string may still be interpreted as valid SQL code, and contain a delimiter to cancel a string the field is inside. This is unlikely, but concerning--a proper database sanitizer is preferred.

2) While the database size is small, Base64 conversions are still relatively wasteful operations compared to proper database sanitization.

**Comment by AlexCMueller** [comment]
P.S. XSS injection is still possible, allowing anyone to send arbitrary, unescaped text over the bot. This isn't terribly significant, but a potential issue.

**Comment by AlexCMueller** [comment]
XSS is slightly escaped-- `@` characters are followed with a zero-width space, so pings aren't possible. Only significance of XSS is buggy text.

**Comment by qixils** [comment]
well, any pings that would matter. you can still "ping" a channel if ye wanted. you can also type a bunch of @ symbols to cause a 2k+ char message ~~but now that i think about it that isn't related to anything~~

**Comment by Bottersnike** [comment]
On the subject of using B64, I threw it in very quickly as a bodge to stop Stuupie SQL-inj-ing the database (it wasn't injecting, but it was crashing the loop). I'll look into better ways to sanitise it, but python doesn't provide sanitation for `WHERE` selectors so the vulnerable part is the `DROP ... WHERE memo = '{}'` because I have no other way of inserting the stuff and using built in sanitation.

**Comment by qixils** [comment]
close as wontfix?

**Comment by Bottersnike** [comment]
Planning to switch to one central database instead of state_cache/*, so yeah, close for now
